@startuml UseCaseDiagram
left to right direction

' =========================
' Actors (from hierarchy in Class Diagram)
' =========================
actor "Customer" as A_Customer
actor "Member" as A_Member
actor "Staff" as A_Staff
actor "Manager" as A_Manager

A_Customer <|-- A_Member
A_Staff <|-- A_Manager

rectangle "Store" {

	'Customer'
	usecase "AddProductToCart" as UC_AddProductToCart
	usecase "ViewCart" as UC_ViewCart
	usecase "RemoveItemFromCart" as UC_RemoveItemFromCart
	usecase "ViewShelf" as UC_ViewShelf
	usecase "ViewProductDetail" as UC_ViewProductDetail
	usecase "Purchase" as UC_Purchase
	usecase "UseCoupon" as UC_UseCoupon
	usecase "Subscribe" as UC_Subscribe

	'Payment'
	usecase "StartPayment" as UC_StartPayment
	usecase "PayViaCard" as UC_PayViaCard
	usecase "PayViaQR" as UC_PayViaQR

	'Member'
	usecase "ApplyDiscountBenefit" as UC_ApplyDiscountBenefit
	usecase "Unsubscribe" as UC_Unsubscribe

	'Staff'
	usecase "CreateCustomer" as UC_CreateCustomer
	usecase "CreateMember" as UC_CreateMember

	'Manager'
	usecase "CreateGame" as UC_CreateGame
	usecase "CreateMachine" as UC_CreateMachine
	usecase "ViewProductStock" as UC_ViewProductStock
	usecase "ViewShelf" as UC_ViewShelf
	usecase "RefillShelf" as UC_RefillShelf
	usecase "CreateCoupon" as UC_CreateCoupon
	usecase "RefillStock" as UC_RefillStock

	'Room Reservation'
	usecase "SearchAvailableRoom" as UC_SearchAvailableRoom
	usecase "CreateReservation" as UC_CreateReservation
	usecase "ViewReservation" as UC_ViewReservation
	usecase "CancelReservation" as UC_CancelReservation
	usecase "CheckIn" as UC_CheckIn
	usecase "ExtendTime" as UC_ExtendTime
	usecase "CheckoutRoom" as UC_CheckoutRoom
	usecase "Refund" as UC_Refund
	usecase "RequestItemForRoom" as UC_RequestItemForRoom
}

'Customer'
A_Customer --> UC_ViewCart
A_Customer --> UC_ViewShelf
A_Customer --> UC_Purchase
A_Customer --> UC_Subscribe
A_Customer --> UC_RequestItemForRoom
A_Customer --> UC_SearchAvailableRoom
A_Customer --> UC_CreateReservation
A_Customer --> UC_ViewReservation
A_Customer --> UC_CheckIn

UC_ViewShelf <.. UC_AddProductToCart : <<extend>>
UC_ViewShelf <.. UC_ViewProductDetail : <<extend>>

UC_ViewProductDetail <.. UC_AddProductToCart : <<extend>>

UC_ViewCart <.. UC_RemoveItemFromCart : <<extend>>

UC_Purchase <.. UC_UseCoupon : <<extend>>
UC_Purchase ..> UC_StartPayment : <<include>>

'Payment'
UC_StartPayment <|-- UC_PayViaCard
UC_StartPayment <|-- UC_PayViaQR

'Member'
A_Member --> UC_ApplyDiscountBenefit
A_Member --> UC_Unsubscribe

'Staff'
A_Staff --> UC_ViewProductStock
A_Staff --> UC_CreateCustomer
A_Staff --> UC_CreateMember
A_Staff --> UC_ViewShelf

UC_CheckIn <.. UC_Refund : <<extend>>
UC_CheckIn <.. UC_ExtendTime : <<extend>>
UC_CheckIn <.. UC_RemoveItemFromCart : <<extend>>
UC_CheckIn <.. UC_CheckoutRoom : <<extend>>

UC_ViewProductStock <.. UC_RefillStock : <<extend>>
UC_ViewShelf <.. UC_RefillShelf : <<extend>>

'Manager'
A_Manager --> UC_CreateCoupon
A_Manager --> UC_ViewProductStock
A_Manager --> UC_CreateGame
A_Manager --> UC_CreateMachine

UC_CreateReservation ..> UC_StartPayment : <<include>>
UC_CreateReservation <.. UC_UseCoupon : <<extend>>
UC_CreateReservation <.. UC_CancelReservation : <<extend>>

@enduml
