@startuml OOP

' =========================
' Platform Root (GamePlatform)
' =========================
class GameStore {
	+name: String
	+user_list: List<User>
	+staff_list: List<Staff>
	+game_list: List<Game>
	+transaction_list: List<Transaction>
	+coupon_list: List<Coupon>
	+room_list: List<Room>
}

' =========================
' Accounts & Roles (Inheritance)
' =========================
abstract class User {
	+id: String
	+display_name: String
	+email: String
	+verified_status: String
	+country: String
	+created_at: DateTime
	+account_status: String  ' Active/Suspended/Closed
}

class Customer {
	+wallet_balance: double
	+refund_count_30d: int
	+friends: List<User>
	+game_copy_list: List<Game>
	+cart: Cart
	+payment_method_list: List<PaymentMethod>
	+transaction_list: List<Transaction>
	+coupon_list: List<Coupon>
}

class Subscriber {
	+member_tier: String
	+expires_at: DateTime
	+extra_discount_rate: double
}

class Publisher {
	+company_name: String
	+kyc_status: String
	+contact_email: String
}

class Staff {
	+employee_id: String
}

class Manager {
}


' =========================
' Game
' =========================
abstract class Game {
	+id: String              ' ex: G-YYYY-XXXX
	+name: String
	+description: String
	+ supported_platform: String
	+image_url: String
	+base_price: double
	+currency: String
	+condition: String          ' New / Used / Badly-Used
	+age_rating: String
	+published_at: DateTime
	+sold_count: int         ' <-- track how many copies sold
	+achievement_list: List<Achievement>
}

class GameDisc {
	+ supported_platform: String	' PC / Console
}
class GameCard {
	+ supported_platform: String	' Switch / Steam Deck
}
class  GameCartridge {
	+ supported_platform: String	' Game Boy
}

class Achievement {
	+achievement_id: String
	+game_id: String
	+name: String
	+image: String
	+rarity: String
}

' =========================
' Game Console
' =========================


' =========================
' Room
' =========================

class Room {
	+max_player_per_room: int
	+max_game: int
}
class VipRoom {
	+max_player_per_room: int
	+max_game: int
}

' =========================
' Coupon
' =========================
class Coupon {
	+id: String
	+value: int
	+minimum_spending: int
	+expire_date: Datetime
}

' =========================
' Cart
' =========================
class Cart {
	+cart_id: String
	+cart_item_list: List<CartItem>
	+total_amount_estimate: double
	+updated_at: DateTime
}

class CartItem {
	+game_copy: Game
	+quantity: int
	+unit_price_estimate: double
}

' =========================
' Transaction / Order (price snapshot + status table)
' =========================
class Transaction {
	+id: String              ' ex: O-YYYYMMDD-XXXX
	+user_id: String
	+status: String          ' PendingPayment/Processing/Completed/Failed/Cancelled
	+created_at: DateTime

	+transaction_item_list: List<TransactionItem>
	+sub_total: double
	+discount_benefit_list: List<DiscountBenefit>
	+discount_total: double
	+total_price: double

	+payment_method: String
	+paid_at: DateTime
}

class TracsactionItem {
	+game_copy: Game
	+quantity: int
	+unit_price: double
	+final_price: double
}

' =========================
' Payment (Abstract)
' =========================
abstract class PaymentMethod {
	+method_id: String
	+status: String  ' Active/Expired/Blocked
}

class CardPayment {
	+brand: String
	+token_ref: String
}

class BankTransferQrPayment {
	+bank_name: String
	+qr_ref: String
}

class WalletPayment {
	+wallet_ref: String
}

' =========================
' Discounts / Entitlements
' =========================
abstract class DiscountBenefit {
	+benefit_id: String
	+status: String  ' Available/Reserved/Consumed/Expired
}

class CouponBenefit {
	+code: String
	+percent_off: double
	+min_spend: double
	+expires_at: DateTime
}

class CreditBenefit {
	+credit_amount: double
	+source: String  ' topup/refund/compensation
}

' =========================
' Refund
' =========================
class RefundRequest {
	+refund_id: String
	+transaction_id: String
	+requested_at: DateTime
	+status: String   ' Requested/UnderReview/Approved/Rejected/Refunded
	+reason: String
}

' =========================================================
' Relationships
' =========================================================

GameStore "1" *-- "0..*" User 
GameStore "1" o-- "0..*" Staff
GameStore "1" o-- "0..*" Game
GameStore "1" o-- "0..*" Transaction
GameStore "1" o-- "0..*" Coupon

User <|-- Publisher
User <|-- Customer

Customer "1" o-- "0..*" PaymentMethod
Customer "1" o-- "0..*" Transaction
Customer "0..*" o-- "0..*" Game
Customer "1" <-- "1" Cart
Customer <|-- Subscriber
Customer "1" o-- "0..*" Coupon

Transaction "1" o-- "0..*" TracsactionItem
Transaction "1" --> "1" RefundRequest
Transaction "1" o-- "0..*" DiscountBenefit

TracsactionItem "1" <-- "1" Game

DiscountBenefit <|-- CouponBenefit
DiscountBenefit <|-- CreditBenefit

Cart "1" o-- "0..*" CartItem

CartItem "1" <-- "1" Game

PaymentMethod <|-- CardPayment
PaymentMethod <|-- BankTransferQrPayment
PaymentMethod <|-- WalletPayment

Staff <|-- Manager

Game "1" *-- "0..*" Achievement
Game <|-- GameDisc
Game <|-- GameCard
Game <|-- GameCartridge

@enduml
