@startuml UseCaseDiagram

' =========================
' Actors (จาก hierarchy ใน Class Diagram)
' =========================
actor "Customer" as A_Customer
actor "Subscriber" as A_Subscriber
actor "Publisher" as A_Publisher
actor "Staff" as A_Staff
actor "Manager" as A_Manager

A_Customer <|-- A_Subscriber
A_Staff <|-- A_Manager

rectangle "GameStore" {
	'Customer'
	usecase "AddGameToCart" as UC_AddGameToCart
	usecase "ViewCart" as UC_ViewCart
	usecase "RemoveItemFromCart" as UC_RemoveItemFromCart
	usecase "ViewStore" as UC_ViewStore
	usecase "ViewGameDetail" as UC_ViewGameDetail
	usecase "Purchase" as UC_Purchase
	usecase "UseCoupon" as UC_UseCoupon

	'Payment'
	usecase "StartPayment" as UC_StartPayment
	usecase "PayViaCard" as UC_PayViaCard
	usecase "PayViaCash" as UC_PayViaCash
	usecase "PayViaQR" as UC_PayViaQR

	'Subscriber'
	usecase "ApplyMemberBenefit" as UC_ApplyMemberBenefit
	usecase "VerifyMember" as UC_VerifyMember
	usecase "Unsubscribe" as UC_Unsubscribe

	'Publisher'
	usecase "PublishGame" as UC_PublishGame
	usecase "ViewPublishedGame" as UC_ViewPublishedGame
	usecase "ViewPublishedGameDetail" as UC_ViewPublishedGameDetail
	usecase "RemoveGame" as UC_RemoveGame
	usecase "FileAppeal" as UC_FileAppeal
	usecase "ViewOrder" as UC_ViewOrder
	usecase "ApproveOrder" as UC_ApproveOrder
	usecase "RejectOrder" as UC_RejectOrder

	'Staff'
	usecase "Checkout" as UC_Checkout
	usecase "ApplyDiscount" as UC_ApplyDiscount
	usecase "CreateMember" as UC_CreateMember

	'Manager'
	usecase "ViewPendingGame" as UC_ViewPendingGame
	usecase "ApproveGame" as UC_ApproveGame
	usecase "RejectGame" as UC_RejectGame
	usecase "ViewReportedGame" as UC_ViewReportedGame
	usecase "RevokeGame" as UC_RevokeGame
	usecase "ViewAppealMail" as UC_ViewAppealMail
	usecase "ApproveAppeal" as UC_ApproveAppeal
	usecase "RejectAppeal" as UC_RejectAppeal
	usecase "RefillShelf" as UC_RefillShelf
	usecase "CreateCoupon" as UC_CreateCoupon
	usecase "OrderGame" as UC_OrderGame
}

'Customer'
A_Customer --> UC_ViewCart
A_Customer --> UC_ViewStore
A_Customer --> UC_Purchase

UC_ViewStore <.. UC_AddGameToCart : <<extend>>
UC_ViewStore <.. UC_ViewGameDetail : <<extend>>

UC_ViewGameDetail <.. UC_AddGameToCart : <<extend>>

UC_ViewCart <.. UC_RemoveItemFromCart : <<extend>>

UC_Purchase <.. UC_UseCoupon : <<extend>>
UC_Purchase ..> UC_StartPayment : <<include>>


'Payment'
UC_StartPayment <|-- UC_PayViaCash
UC_StartPayment <|-- UC_PayViaCard
UC_StartPayment <|-- UC_PayViaQR

'Subscriber'
A_Subscriber --> UC_ApplyMemberBenefit
A_Subscriber --> UC_Unsubscribe

UC_ApplyMemberBenefit ..> UC_VerifyMember : <<include>>

'Publisher'
A_Publisher --> UC_PublishGame
A_Publisher --> UC_ViewPublishedGame
A_Publisher --> UC_ViewOrder

UC_ViewOrder <.. UC_ApproveOrder : <<extend>>
UC_ViewOrder <.. UC_RejectOrder : <<extend>>

UC_ViewPublishedGame <.. UC_RemoveGame : <<extend>>
UC_ViewPublishedGame <.. UC_ViewPublishedGameDetail : <<extend>>
UC_ViewPublishedGame <.. UC_FileAppeal : <<extend>>

'Staff'
A_Staff --> UC_Checkout
A_Staff --> UC_RefillShelf
A_Staff --> UC_CreateMember

UC_Checkout <.. UC_ApplyDiscount : <<extend>>

'Manager'
A_Manager --> UC_ViewReportedGame
A_Manager --> UC_ViewAppealMail
A_Manager --> UC_ViewPendingGame
A_Manager --> UC_CreateCoupon
A_Manager --> UC_OrderGame

UC_ViewReportedGame <.. UC_RevokeGame : <<extend>>

UC_ViewAppealMail <.. UC_ApproveAppeal : <<extend>>
UC_ViewAppealMail <.. UC_RejectAppeal : <<extend>>

UC_ViewPendingGame <.. UC_ApproveGame : <<extend>>
UC_ViewPendingGame <.. UC_RejectGame : <<extend>>


@enduml