@startuml UsecaseSequenceDiagram

actor Customer as A_Customer
participant GameStore
participant Customer as P_Customer
participant Member
participant PaymentGateway
participant Bill
participant Logs

A_Customer -> GameStore : subscribe(customer_id, payment_gateway_name, payment_information)
activate A_Customer
activate GameStore

alt subscribe success

	loop get customer by id

		GameStore -> P_Customer : Get customer
		activate P_Customer

		P_Customer -> GameStore : Customer
		deactivate P_Customer

	end

	loop get member by customer id

		GameStore -> Member : Get member
		activate Member

		Member -> GameStore : Member / None
		deactivate Member

	end

	loop get payment gateway by name

		GameStore -> PaymentGateway : Get payment gateway
		activate PaymentGateway

		PaymentGateway -> GameStore : PaymentGateway
		deactivate PaymentGateway

	end

	GameStore -> PaymentGateway : start_payment(payment_information, 500)
	activate PaymentGateway

	PaymentGateway -> GameStore : Success
	deactivate PaymentGateway

	GameStore -> Bill : create_bill(payment_gateway, 500)
	activate Bill
	Bill -> GameStore : Bill
	deactivate Bill

	GameStore -> P_Customer : add_bill(Bill)
	activate P_Customer
	P_Customer -> GameStore
	deactivate P_Customer

	alt existing member but inactive

		GameStore -> Member : set_status(ACTIVE)
		activate Member
		Member -> GameStore : Member
		deactivate Member

		GameStore -> Logs : create_customer_logs(Customer, SUBSCRIBE)
		activate Logs
		Logs -> GameStore : Log
		deactivate Logs

		GameStore -> A_Customer : member

	else create new member

		GameStore -> Member : create_member(Customer)
		activate Member
		Member -> GameStore : Member
		deactivate Member

		GameStore -> Logs : create_customer_logs(Customer, SUBSCRIBE)
		activate Logs
		Logs -> GameStore : Log
		deactivate Logs

		GameStore -> A_Customer : new_member

	end

else subscribe fail (customer not found)

	P_Customer -> GameStore : Fail (customer not found)
	GameStore -> A_Customer : Customer not found

else subscribe fail (already active member)

	Member -> GameStore : Fail (already active member)
	GameStore -> A_Customer : Fail already be a member

else subscribe fail (payment gateway not found)

	PaymentGateway -> GameStore : Fail (payment gateway not found)
	GameStore -> A_Customer : Payment gateway not found

else subscribe fail (fail to payment)

	PaymentGateway -> GameStore : Failed
	GameStore -> A_Customer : Fail to payment

end

deactivate GameStore
deactivate A_Customer

@enduml