@startuml SequenceDiagramCreateGame

actor Manufacturer as A_Manufacturer

participant Manufacturer as P_Manufacturer
participant Game
participant StockProduct

A_Manufacturer -> P_Manufacturer : create_game(name, description, genre, supported_platform)
activate P_Manufacturer

P_Manufacturer -> Game : create_game(name, description, genre, supported_platform)
activate Game

Game -> P_Manufacturer : Game
deactivate Game

P_Manufacturer -> StockProduct : create_new_stock(product)
activate StockProduct

StockProduct -> P_Manufacturer : StockProduct
deactivate StockProduct

P_Manufacturer -> A_Manufacturer : game_id
deactivate P_Manufacturer

@enduml