@startuml UsecaseSequenceDiagram

actor Customer as A_Customer
participant GameStore
participant Customer as P_Customer
participant Room
participant Reservation
participant Log

A_Customer -> GameStore : create_reservation(customer_id, room_id, start_time, end_time)
activate A_Customer
activate GameStore

alt create reservation success

	loop get customer by id

		GameStore -> P_Customer : Get customer
		activate P_Customer

		P_Customer -> GameStore : Customer
		deactivate P_Customer

	end

	GameStore -> P_Customer : check_time_availability(start_time, end_time)
	activate P_Customer

	P_Customer -> GameStore : Available
	deactivate P_Customer

	loop get room by id

		GameStore -> Room : Get room
		activate Room

		Room -> GameStore : Room
		deactivate Room

	end

	GameStore -> Room : create_reservation(customer, start_time, end_time)
	activate Room

	Room -> Reservation : create_reservation(customer, start_time, end_time)
	activate Reservation
	Reservation -> Room : Reservation
	deactivate Reservation

	Room -> GameStore : Reservation
	deactivate Room

	GameStore -> P_Customer : add_reservation(reservation)
	activate P_Customer
	P_Customer -> GameStore
	deactivate P_Customer

	GameStore -> Log : create_customer_logs(customer, CREATE_RESERVATION)
	activate Log
	Log -> GameStore : Log
	deactivate Log

	GameStore -> A_Customer : reservation.id

else create reservation fail (invalid user)

	P_Customer -> GameStore : Fail (invalid user)
	GameStore -> A_Customer : Invalid User

else create reservation fail (invalid time frame)

	P_Customer -> GameStore : Fail (invalid time frame)
	GameStore -> A_Customer : Invalid Time Frame

else create reservation fail (no room this id)

	Room -> GameStore : Fail (no room this id)
	GameStore -> A_Customer : No Room this ID

else create reservation fail (fail to create reservation)

	Room -> GameStore : Fail (invalid time frame)
	GameStore -> A_Customer : Invalid Time Frame

end

deactivate GameStore
deactivate A_Customer

@enduml