@startuml E

actor Manager as ManagerA

ManagerA -> GameStore : refill_stock(manager_id, stock_id, quantity, sell_price)
activate ManagerA
activate GameStore

loop Find manager instance by ID
    GameStore -> Manager
    activate Manager
    Manager -> GameStore
    deactivate Manager
end

alt Did find manager instance
    loop Find stock by id
        GameStore -> StockProduct
        activate StockProduct
        StockProduct -> GameStore
        deactivate StockProduct
    end

    alt Did find StockProduct
        alt quantity is more than zero
            alt sell_price is more than zero
                GameStore -> StockProduct : refill_stock(quantity, sell_price)
                activate StockProduct
                loop loop for total of quantity times
                    StockProduct -> ProductItem : Create product item
                    activate ProductItem
                    ProductItem -> StockProduct : Return product item instance for storing
                    deactivate ProductItem
                end
                StockProduct -> GameStore
                deactivate StockProduct

                GameStore -> Log : create_log(manager_instance, ManagerAction.REFILL_STOCK, stock_product)
                activate Log
                Log -> GameStore : Return instance for storing
                deactivate Log

                GameStore -> ManagerA : stock_product
            else
                GameStore -> ManagerA : Failed (Invalid sell_price)
            end
        else 
            GameStore -> ManagerA : Failed (Invalid quantity)
        end
    else Did not find
        GameStore -> ManagerA : Failed (Invalid product ID)
    end
else Did not find manager instance
    GameStore -> ManagerA : Failed (Invalid manager ID)
end

deactivate GameStore
deactivate ManagerA

@enduml