@startuml E

actor Customer as CustomerA

CustomerA -> GameStore : purchase(customer_id, payment_method_name, payment_info, coupon_info)
activate CustomerA
activate GameStore

loop Get customer instance by id
    GameStore -> Customer : Get customer
    activate Customer
    Customer -> GameStore : Customer
    deactivate Customer
end

alt Store did have that customer instance
    loop Get payment method by name
        GameStore -> PaymentMethod : Get payment method
        activate PaymentMethod
        PaymentMethod -> GameStore : Payment method
        deactivate PaymentMethod
    end

    alt Payment method with same name exist
        GameStore -> Customer : Get customer's cart
        activate Customer
        Customer -> Cart : Get cart
        activate Cart
        Cart -> Customer : Return cart
        deactivate Cart
        Customer -> GameStore : Return Cart
        deactivate Customer

        GameStore -> Cart : Get CartItem list
        activate Cart
        Cart -> CartItem : Get CartItem list
        activate CartItem
        CartItem -> Cart : Return CartItem list
        deactivate CartItem
        Cart -> GameStore : Return CartItem list
        deactivate Cart

        loop Get all the product items that the customer choose to buy, sum the price and check if is selling
            GameStore -> CartItem
            activate CartItem
            CartItem -> GameStore
            deactivate CartItem
        end
        
        alt All the product item have a selling status
            GameStore -> Customer : Get customer discount benefit
            activate Customer
            Customer -> GameStore : Return the discount benefit
            deactivate Customer
            GameStore -> GameStore : Apply the discount benefit to the sum of the product pricing
            activate GameStore
            deactivate GameStore

            alt Coupon ID is specified
                GameStore -> Customer : Get coupon from ID
                activate Customer
                loop Get coupon
                    Customer -> Coupon
                    activate Coupon
                    Coupon -> Customer
                    deactivate Coupon
                end
                Customer -> GameStore : Return Coupon
                deactivate Customer

                GameStore -> Coupon : Check if the purchasing is valid for coupon application
                activate Coupon
                Coupon -> GameStore
                deactivate Coupon

                alt Coupon is invalid
                    GameStore -> CustomerA : Failed (Unable to apply coupon)
                end

                GameStore -> GameStore : Apply coupon
                activate GameStore
                deactivate GameStore
            end

            GameStore -> PaymentMethod : start_payment(total_pricing, payment_info)
            activate PaymentMethod
            PaymentMethod -> GameStore : Return Status
            deactivate PaymentMethod

            alt Payment successful
                loop Set the product item status to be sold
                    GameStore -> CartItem : Access the product item
                    activate CartItem
                    CartItem -> ProductItem : Set the status to being sold
                    activate ProductItem
                    ProductItem -> CartItem
                    deactivate ProductItem
                    CartItem -> GameStore
                    deactivate CartItem
                end

                GameStore -> Bill : create_bill(payment_method, total_pricing)
                activate Bill
                Bill -> GameStore : Return Bill
                deactivate Bill

                GameStore -> Bill : Add the purchased items
                activate Bill
                Bill -> GameStore : Store bill
                deactivate Bill

                GameStore -> Log : create_customer_logs(customer_instance, CustomerAction.Purchase)
                activate Log
                Log -> GameStore : Store log
                deactivate Log

                GameStore -> CustomerA : Return bill and product item serial number
            else
                GameStore -> CustomerA : Failed (Payment failed)
            end
        else
            GameStore -> CustomerA : Failed (Product is unavailable)
        end
    else
        GameStore -> CustomerA : Failed (Payment method doesn't exist)
    end
else
    GameStore -> CustomerA : Failed (You don't exist)
end



deactivate GameStore
deactivate CustomerA

@enduml