@startuml UsecaseSequenceDiagram

actor Customer as A_Customer
participant GameStore
participant Customer as P_Customer
participant Member
participant PaymentGateway
participant Bill
participant Logs

activate A_Customer

A_Customer -> GameStore : subscribe(customer_id, payment_gateway, payment_information)
activate GameStore

loop get_customer_from_id

	GameStore -> P_Customer : get_customer()
	activate P_Customer

	P_Customer -> GameStore : Customer
	deactivate P_Customer

end

alt Found User

	loop get_member_from_customer_id

		GameStore -> Member : get_member()
		activate Member

		Member -> GameStore : Member
		deactivate Member

	end

	alt Not already member

		GameStore -> PaymentGateway : start_transaction(payment_information, amount)
		activate PaymentGateway

		alt Success

			PaymentGateway -> GameStore : Success

		else Fail

			PaymentGateway -> GameStore : Failed
			deactivate PaymentGateway

			GameStore -> A_Customer : Payment Failed

		end

		GameStore -> Bill : create_bill(Customer, amount)
		activate Bill

		Bill -> GameStore : Bill
		deactivate Bill

		GameStore -> P_Customer : add_bill(Bill)
		activate P_Customer

		P_Customer -> GameStore
		deactivate P_Customer

		GameStore -> Member : create_member(Customer)
		activate Member

		Member -> GameStore : Member
		deactivate Member

		GameStore -> Logs : create_logs(Customer, customer_action)
		activate Logs

		Logs -> GameStore : Log
		deactivate Logs

		GameStore -> A_Customer : member_id

	else Already Member

		GameStore -> A_Customer : Fail already member

	end

else Not found user

	GameStore -> A_Customer : Fail to find user
	deactivate GameStore
end

deactivate A_Customer

@enduml
