@startuml name

actor Customer

activate Customer
Customer -> GameStore : check_in(customer_id)

loop
activate GameStore
GameStore -> Staff: find_available_staff()

activate Staff
Staff -> GameStore: Staff
deactivate Staff
end

GameStore -> Reservation: check_in(customer, staff)
activate Reservation
Reservation -> GameStore: Reservation
deactivate Reservation

GameStore -> Room: set_room_status()
activate Room
Room -> Room: occupied?
Room -> GameStore: Room
deactivate Room

GameStore -> Transaction: create_transaction(customer, reservation)
activate Transaction
Transaction -> GameStore: Transaction
deactivate Transaction

GameStore -> Customer : check_in_response(status)
deactivate GameStore

deactivate Customer

@enduml
