@startuml ClassDiagram

' Service
class GameStore
{
	- id: String
	- name: String

	- shelf_list : List<Shelf>
	- stock_product_list: List<StockProduct>

	- room_list: List<Room>

	- customer_list: List<Customer>
	- member_list: List<Member>
	- staff_list: List<Staff>

	- payment_method_list: List<PaymentMethod>
	- product_proposal_list: List<Product>

	- room_Logs_list: List<RoomLogs>
	- product_Logs_list: List<ProductLogs>

	- bill: Bill

	+ make_reservation(customer: Customer, room: Room)
	+ create_customer(name: str)
	+ create_member_plus(customer: Customer)
	+ create_Logs()
	+ start_payment()
	+ apply_discount()
}

' Shelf
class Shelf
{
	- max_capacity: int
	- product_on_shelf: List<ProductItem>

	+ view_shelf()
	+ item_to_cart(item_id: str, cart: Cart)
	+ fill_product(product_item_list: List<ProductItem>)
}

' Product
class StockProduct
{
	- product: Product
	- product_item_list: List<ProductItem>
}

abstract class Product
{
	- name: String
	- id: String
	- manufacturer: Manufacturer
	- sell_price: int
}

class ProductItem
{
	- product: Product
	- serial_number: String
	- status: String
	' Waiting_For_Approval, Selling, For_Rental, Unavailable, Removed
	- condition: String
	' New, Second_Hand, Refurbish
}

' Game
abstract class Game
{
	- name: String
	- description: String
	- genre: List<String>
	- supported_platform: List<String>
	- status: String
	' Waiting_For_Approval, Selling, For_Rental, Unavailable, Under_Maintainace, Removed

	+ play()
}

class GameDisc
{
	+ play()
}

class GameKeyCard
{
	+ play()
}

class GameCartridge
{
	+ play()
}

' Room
class Room
{
	- id: String
	- max_customer: int
	- serivce_price: int
	- room_type: RoomTypeEnum

	- status: String
	' Available, Reserved, Being-Use, Under-Maintainace

	- available_product: List<ProductItem>

	+ set_status(status: Enum)
	+ create_reservation(self, customer: Customer) -> Reservation
}

Enum RoomType
{
	- NORMAL
	- VIP
}

Enum RoomStatus
{
	- AVAILABLE
	- RESERVED
	- MAINTAINACE
	- IN_USE
}

' Reservation
class Reservation
{
	- id: String

	- customer: Customer
	- room: Room

	- status: String
	' Pending, Paid, Serivced, Cancel
	- time_start: Datetime
	- end_start: Datetime

	+ set_status(status: Enum)
}

' Machine
abstract class Machine
{
	- status: String
	' Waiting_For_Approval, Selling, For_Rental, Unavailable, Under_Maintainace, Removed

	+ run_game()
}

class PC
{
	- cpu: String
	- gpu: String
	- mem: int

	+ run_game()
}

class Playstation
{
	+ run_game()
}

class Switch
{
	+ run_game()
}

class GameBoi
{
	+ run_game()
}

' Role
class Customer
{
	- name: String
	- id: String

	- coupon_list: List<Coupon>
	- payment_method_list: List<PaymentMethod>

	- cart: Cart
	- reservation: Reservation
	- service_history: List<Logs>
	- bought_product: List<ProductItem>

	- bill: Bill

	+ add_to_cart(productId: str)
	+ remove_from_cart(productId: str)

	+ buy_product()
	+ refund_product(productItem: ProductItem)

	+ reserve_room(roomId: str)
	+ check_in()
	+ check_out()

	+ discount()
}

class Member
{
	- member_expire_date: Datetime
	- member_stamp: MemberStamp
	- member_discount: float
	' 5% or something

	+ unsubscribe()
	+ stamp(staffId: str)
	+ discount()
}

class Staff
{
	- name: String
	- id: String
	- store: GameStore

	+ shelf_restock(shelf: Shelf, product: Product, amount: int)
	+ check_in()
	+ check_out()
}

class Manager
{
	+ approve_product_proposal(product : Product)
	+ order_product(manufacturer: Manufacturer, store: GameStore, product: Product, quantity: int)
}

class Manufacturer
{
	- name: String
	- id: String
	- product_list: List<Product>
	- product_stock_lsit: List<StockProduct>
	- bill: Bill

	+ propose_product(store, product)
	+ supply_product(store: GameStore, product: Product, quantity: int)
	+ create_product_item(product: Product, amount: int)
	+ view_product_stock()
	' Create Product Item (unique item)
	+ create_game(name: str, supported_platform: Machine)
	+ refill_game_stock(product_stock: List<StockProduct>, amount: int)
	' Create Game
	+ create_machine(name: str)
	+ refill_machine_stock(product_stock: List<StockProduct>, amount: int)
	' Create Machine
}

' Cart
class Cart
{
	- owner: Customer
	- cart_item_list: list<CartItem>

	+ add_item(product: ProductItem)
	+ remove_item(product: ProductItem)
}

class CartItem
{
	- is_buy: bool
	- productItem: ProductItem
}

' Discount
abstract class Discount
{
	- owner: Customer
	- discount: int
	- expire_date: Datetime
}

class MemberStamp
{
	- points: int
	- max_point: int

	+ add_point(amount: )
}

class Coupon
{
	- minimum_spending: int
}

' Payment Method
abstract class PaymentMethod
{
	- id: String
	- status: String
	' Active/Expired/Blocked

	+ authenticate()
	+ pay()
}

class QrCode
{
	- bank_name: String
	- qr_ref: String
	
	+ authenticate()
	+ pay()
}

class Card
{
	- brand: String
	- token_ref: String

	+ authenticate()
	+ pay()
}

' Logs
abstract class Log
{
	- id: String
}

class CustomerLog
{
	- actor: Customer
	- action: CustomerLogAction
}

Enum CustomerLogAction
{
	- BUY
	- RENT
	- RESERVE
	- CANCEL_RESERVE
	- REFUND
}

class StaffLog
{
	- actor: Staff
	- action: StaffLogAction
}

Enum StaffLogAction
{
	- CHECK_IN
	- CHECK_OUT
	- REFILL_SHELF
}

class ManagerLog
{
	- actor: Manager
	- action: ManagerLogAction
}

Enum ManagerLogAction
{
	- APPROVE_PRODUCT
	- DISAPPROVE_PRODUCT
	- ORDER_PRODUCT
}

abstract class Bill
{
	- id: String
	- timestamp: Datetime
	- payment_method: PaymentMethod
	- amount: float
}

class ProductBill
{
	- product_item_list: List<ProductItemList>
}

class RoomBill
{
	- reservation: Reservation
}

' Relation
GameStore "1" o-- "0..*" StockProduct
GameStore "1" o-- "0..*" Shelf
GameStore "1" o-- "1..*" Room
GameStore "1" o-- "0..*" Customer
GameStore "1" *-- "0..*" Member
GameStore "1" o-- "1..*" Staff
GameStore "1" o-- "1..*" PaymentMethod
GameStore "1" o-- "0..*" Log
GameStore "1" o-- "0..*" Bill

Shelf "0" o-- ProductItem

StockProduct --> Product
StockProduct o-- ProductItem

Product <|-- Game
Product <|-- Machine
Product "1" --o "o..*" Manufacturer

ProductItem --> Product

Game <|-- GameDisc
Game <|-- GameKeyCard
Game <|-- GameCartridge

Room o-- Reservation
Room --> RoomStatus
Room --> RoomType
Room o-- ProductItem

Machine <|-- PC
Machine <|-- Switch
Machine <|-- GameBoi
Machine <|-- Playstation

Customer "0..*" *-- Coupon
Customer "1" <-> "1" Cart
Customer o-- Reservation
Customer o-- Bill
Customer <|-- Member

Member --> "1" MemberStamp

Staff <|-- Manager

Cart o-- CartItem

CartItem --> ProductItem

Discount <|-- MemberStamp
Discount <|-- Coupon
Discount --> "1" Customer
Discount "1" <-- Logs

PaymentMethod <|-- QrCode
PaymentMethod <|-- Card

Log <|-- CustomerLog
Log <|-- StaffLog
Log <|-- ManagerLog

CustomerLog --> CustomerLogAction
StaffLog --> StaffLogAction
ManagerLog --> ManagerLogAction

StaffLogAction <|-- ManagerLogAction

Reservation --> Room

Manufacturer o-- Product
Manufacturer o-- Bill
Manufacturer o-- StockProduct

Bill <|-- ProductBill
Bill <|-- RoomBill

@enduml